### PR TITLE
Implement hover

### PR DESCRIPTION
**Pull request by xanf**

### CODE REVIEW

**Comment by rtorr** [comment]
👍👍👍👍👍

**Comment by xanf** [comment]
@rtorr Actually i'm thinking of closing this three pull requests and merging into one. After playing a night with code it seems we need a bit more changes everythere:
- remove no-auto-start - flow seems to handle pretty well autostarting
- tune helper so we will not raise error output if flow ended with code 0 - that will prevent spamming things like "flow server is still starting..."
- switch to [cross-spawn](https://www.google.com.ua/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=cross-spawn%20npm) instead of spawn - i had problems with files with spaces on windows
- remove license from FB - i asked my facebook colleagues (I'm not working for facebook) - they say there is nothing which should be licensed here - it's just boilerplate extension code and flow invocation

If you're fine with it - i will open one big pull with all that changes. Actually I really like simple `flow` invocation over dark nuclide magic

**Comment by rtorr** [comment]
I'm cool with the that

**Comment by ajhyndman** [comment]
I'd be happy to pitch in, if anyone thinks its worth the time to bring me up to speed.

It sounds like you're pretty close though.

**Comment by rtorr** [comment]
@xanf the history with some of the Facebook license stuff is because it references some of their code/I was hoping to merge this back into the main project, which probably won't happen now. I'm cool with removing them now as there is no shared code.

**Comment by rtorr** [comment]
I'm going to merge all three into one non master branch

**Comment by rtorr** [comment]
@ajhyndman feel free to give anything a try :D

**Pull request merged**
