### PR TITLE
Update Flow to v0.30.0 + Windows support

### PR DESCRIPTION
**Pull request by fhelwanger**
Flow v0.30.0 now has Windows support :tada: :balloon: 

This PR changes two things:
- Update Flow binaries in all platforms.
- Remove error message saying that Flow isn't supported on Windows.

### CODE REVIEW

**Comment by rtorr** [comment]
@fhelwanger are you using this extension? Will look into publishing this over the weekend. 

Check out this issue https://github.com/rtorr/vscode-flow/issues/1#issuecomment-234317764

**Comment by fhelwanger** [comment]
@rtorr Now that flow is supported on Windows, I tried to use this extension and https://github.com/flowtype/flow-for-vscode, but both didn't work at first.

At first, I tried to make `flow-for-vscode` work, but I gave up on some errors on some nuclide packages. Then I tried this extension and, after some little tweaks, it worked very well on my tests :smile: 

When it gets published I'll definitely use it.

**Comment by rtorr** [comment]
@fhelwanger What i'm trying to suggest is once they release that PR, that will probably be the go-to flow extension. https://github.com/flowtype/flow-for-vscode/pull/19#discussion_r70846888

If I have time, I will try and merge this in.

**Comment by rtorr** [comment]
Having some issues publishing, waiting to hear back on https://github.com/Microsoft/vscode-vsce/issues/114

**Comment by fhelwanger** [comment]
@rtorr Got it, thanks.

**Comment by f4k3N4m3** [comment]
@rtorr it seem that they fix it.

**Comment by rtorr** [comment]
This is now published

**Pull request merged**
